### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by athphane** [tropicoo/yt-dlp-bot#133]
Is there a way to allow multiple users to use the bot? Apart from the group method. i want to be able to share the bot with other users and let them DM the bot directly.

**Comment by tropicoo** [comment]
Yes, you just need to add another user section in the config file. In the example-config file you can see that there's only one user:
```yaml
  allowed_users:
    - id: 00000000000
      send_startup_message: !!bool True
      download_media_type: !!str "VIDEO"
      save_to_storage: !!bool False
      use_url_regex_match: !!bool True
      upload:
        upload_video_file: !!bool False
        upload_video_max_file_size: 2147483648
        forward_to_group: !!bool False
        forward_group_id: -00000000000
        silent: !!bool False
        video_caption:
          include_title: !!bool True
          include_filename: !!bool False
          include_link: !!bool True
          include_size: !!bool True
```

To add another one you just need to copy the whole user section:
```yaml
  allowed_users:
    - id: 00000000000
      send_startup_message: !!bool True
      download_media_type: !!str "VIDEO"
      save_to_storage: !!bool False
      use_url_regex_match: !!bool True
      upload:
        upload_video_file: !!bool False
        upload_video_max_file_size: 2147483648
        forward_to_group: !!bool False
        forward_group_id: -00000000000
        silent: !!bool False
        video_caption:
          include_title: !!bool True
          include_filename: !!bool False
          include_link: !!bool True
          include_size: !!bool True
    - id: 11111111111111111
      send_startup_message: !!bool True
      download_media_type: !!str "VIDEO"
      save_to_storage: !!bool False
      use_url_regex_match: !!bool True
      upload:
        upload_video_file: !!bool False
        upload_video_max_file_size: 2147483648
        forward_to_group: !!bool False
        forward_group_id: -00000000000
        silent: !!bool False
        video_caption:
          include_title: !!bool True
          include_filename: !!bool False
          include_link: !!bool True
          include_size: !!bool True
```
