### ISSUE TITLE
Bot should work independently in groups.

### ISSUE THREAD

**Issue by ShamilSd-ux** [tropicoo/yt-dlp-bot#184]
By the architecture of bot. We can send only links to the bot and the content is forwarded to a single group. There are use cases where if bot is added to a group then a link posted in the group gets rendered and video is posted in the group. By this functionality we can use bot in many groups simultaneously. I humbly request developer to include this functionality...

**Comment by tropicoo** [comment]
That functionality already is implemented. You need to put the group (chat) id into the config like for the regular user. Then you must add the bot with privileges to that group and it should work since I use that functionality.

**Comment by ShamilSd-ux** [comment]
Are you pasting link in group?

**Comment by ShamilSd-ux** [comment]
Like I said you are assuming the functionality i mentioned but it is not there. Kindly look into that please...

**Comment by tropicoo** [comment]
1. Remove the bot from your group
2. By default, Group Privacy is enabled for bots. This setting has to be changed used the `@BotFather` bot >> `/mybots` >>  `@YOUR_BOT` >>  `Bot Settings` >> `Group Privacy` >> `Turn off`
3. Add the bot back to the group
4. Open `Manage group` >> `Members`. Look that `YOUR_BOT has access to messages` text
5. Paste the video URL, check that bot reacted

**Comment by ShamilSd-ux** [comment]
I have done above steps yet it's like the same. Kindly post a screenshot...

**Comment by ShamilSd-ux** [comment]
Please, I want to close this issue today. It's eating me for months...

**Comment by tropicoo** [comment]
Sure
![image](https://github.com/tropicoo/yt-dlp-bot/assets/888784/b13f3d36-1299-4bca-b2ba-61d637d36f99)

**Comment by tropicoo** [comment]
Are you sure that the group ID is correct in your config? It should start with minus (`-`) and then an integer number, e.g. `-1234567890`

**Comment by ShamilSd-ux** [comment]
![Screenshot 2023-10-04 013647](https://github.com/tropicoo/yt-dlp-bot/assets/81691084/db6a38df-7a8f-40c7-889f-a9a53e08cd73)
My config is like this

**Comment by tropicoo** [comment]
You must create a new section for group ID in the same manner as it's defined for your User:

```yaml
  allowed_users:  # Multiple users/groups are allowed.
    - id: 11111111111  # User ID.
      send_startup_message: !!bool True
      download_media_type: "VIDEO"
      save_to_storage: !!bool False
      use_url_regex_match: !!bool True
      upload:
        upload_video_file: !!bool False
        upload_video_max_file_size: 2147483648
        forward_to_group: !!bool False
        forward_group_id: -00000000000  # Group or channel ID.
        silent: !!bool False
        video_caption:
          include_title: !!bool True
          include_filename: !!bool False
          include_link: !!bool True
          include_size: !!bool True
    - id: -1234567890  # Group ID.
      send_startup_message: !!bool True
      download_media_type: "VIDEO"
      save_to_storage: !!bool False
      use_url_regex_match: !!bool True
      upload:
        upload_video_file: !!bool False
        upload_video_max_file_size: 2147483648
        forward_to_group: !!bool False
        forward_group_id: -00000000000  # Group or channel ID.
        silent: !!bool False
        video_caption:
          include_title: !!bool True
          include_filename: !!bool False
          include_link: !!bool True
          include_size: !!bool True
```
