### ISSUE TITLE
Modification for Stable Version

### ISSUE THREAD

**Issue by ShamilSd-ux** [tropicoo/yt-dlp-bot#312]
I   need just the latest stable version of yt-dlp. Where should I modify the code for that?

**Comment by tropicoo** [comment]
In `config.yaml`:
```yaml
...
ytdlp:
  version_check_enabled: !!bool True
  version_check_interval: 86400
  notify_users_on_new_version: !!bool True
  release_channel: "NIGHTLY"   # <------------------ Change here to STABLE or MASTER
```
More details https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#update
